version: '3'


services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - birabar


  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-container
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - birabar


  backend:
    build:
      context: ./backend
    image: backend-image
    container_name: backend-container
    environment:
      - MONGODB_URI=mongodb://root:root@mongodb-container:27017/restobarbd?authSource=admin
    ports:
      - "3000:3000"
    networks:
      - birabar


  frontend:
    build:
      context: ./frontend
    image: frontend-image
    container_name: frontend-container
    ports:
      - "80:80"
    networks:
      - birabar


networks:
  birabar:
    driver: bridge
